# K-Mean Clustering

# Importing Libraries

In [1]:
import cv2
import numpy as np

# Reading An Image

In [2]:
img = cv2.imread("C:/Users/MR.H.BALAJEE/Downloads/german shepherd.jpeg")
img

array([[[114, 211, 161],
        [114, 211, 161],
        [114, 211, 161],
        ...,
        [123, 222, 166],
        [123, 222, 166],
        [123, 222, 166]],

       [[114, 211, 161],
        [114, 211, 161],
        [114, 211, 161],
        ...,
        [124, 223, 167],
        [124, 223, 167],
        [124, 223, 167]],

       [[114, 211, 161],
        [114, 211, 161],
        [114, 211, 161],
        ...,
        [125, 224, 168],
        [125, 224, 168],
        [125, 224, 168]],

       ...,

       [[ 59, 179, 125],
        [ 60, 180, 126],
        [ 64, 184, 130],
        ...,
        [ 58, 169, 117],
        [ 51, 162, 110],
        [ 34, 145,  93]],

       [[ 57, 177, 123],
        [ 58, 178, 124],
        [ 61, 181, 127],
        ...,
        [ 91, 202, 150],
        [ 77, 188, 136],
        [ 49, 160, 108]],

       [[ 63, 183, 129],
        [ 63, 183, 129],
        [ 64, 184, 130],
        ...,
        [102, 213, 161],
        [ 83, 194, 142],
        [ 48, 159, 107]]

# GRB Conversion

In [3]:
imgrgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
imgrgb

array([[[161, 211, 114],
        [161, 211, 114],
        [161, 211, 114],
        ...,
        [166, 222, 123],
        [166, 222, 123],
        [166, 222, 123]],

       [[161, 211, 114],
        [161, 211, 114],
        [161, 211, 114],
        ...,
        [167, 223, 124],
        [167, 223, 124],
        [167, 223, 124]],

       [[161, 211, 114],
        [161, 211, 114],
        [161, 211, 114],
        ...,
        [168, 224, 125],
        [168, 224, 125],
        [168, 224, 125]],

       ...,

       [[125, 179,  59],
        [126, 180,  60],
        [130, 184,  64],
        ...,
        [117, 169,  58],
        [110, 162,  51],
        [ 93, 145,  34]],

       [[123, 177,  57],
        [124, 178,  58],
        [127, 181,  61],
        ...,
        [150, 202,  91],
        [136, 188,  77],
        [108, 160,  49]],

       [[129, 183,  63],
        [129, 183,  63],
        [130, 184,  64],
        ...,
        [161, 213, 102],
        [142, 194,  83],
        [107, 159,  48]]

# Reshape

In [4]:
vec = imgrgb.reshape((-1,3))
vec

array([[161, 211, 114],
       [161, 211, 114],
       [161, 211, 114],
       ...,
       [161, 213, 102],
       [142, 194,  83],
       [107, 159,  48]], dtype=uint8)

# Float Conversion

In [5]:
vec = np.float32(vec)
vec

array([[161., 211., 114.],
       [161., 211., 114.],
       [161., 211., 114.],
       ...,
       [161., 213., 102.],
       [142., 194.,  83.],
       [107., 159.,  48.]], dtype=float32)

# Iteration Termination Criteria

In [6]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,1)
criteria

(3, 100, 1)

# Cluster Conditions

In [7]:
k = 3
attempts = 100

# K-Means Clustering 

In [8]:
compactness,label,center = cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)

In [9]:
compactness

89411920.3586955

In [10]:
label

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [2]], dtype=int32)

In [11]:
center

array([[163.96266 , 208.2239  , 107.21338 ],
       [ 68.09353 ,  50.625492,  32.75567 ],
       [138.99207 , 156.53926 ,  68.05368 ]], dtype=float32)

# Unit Conversion

In [12]:
center = np.uint8(center)
center

array([[163, 208, 107],
       [ 68,  50,  32],
       [138, 156,  68]], dtype=uint8)

# Flattening and Reshape

In [13]:
res = center[label.flatten()]
res_img = res.reshape((imgrgb.shape))
res_img

array([[[163, 208, 107],
        [163, 208, 107],
        [163, 208, 107],
        ...,
        [163, 208, 107],
        [163, 208, 107],
        [163, 208, 107]],

       [[163, 208, 107],
        [163, 208, 107],
        [163, 208, 107],
        ...,
        [163, 208, 107],
        [163, 208, 107],
        [163, 208, 107]],

       [[163, 208, 107],
        [163, 208, 107],
        [163, 208, 107],
        ...,
        [163, 208, 107],
        [163, 208, 107],
        [163, 208, 107]],

       ...,

       [[138, 156,  68],
        [138, 156,  68],
        [138, 156,  68],
        ...,
        [138, 156,  68],
        [138, 156,  68],
        [138, 156,  68]],

       [[138, 156,  68],
        [138, 156,  68],
        [138, 156,  68],
        ...,
        [163, 208, 107],
        [138, 156,  68],
        [138, 156,  68]],

       [[138, 156,  68],
        [138, 156,  68],
        [138, 156,  68],
        ...,
        [163, 208, 107],
        [163, 208, 107],
        [138, 156,  68]]

# Original and Segmented Image

In [ ]:
cv2.imshow("Original Image", img)
cv2.imshow("Segmented Image", res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()