# Image Rotation and Translation 

In [1]:
import cv2
import numpy as np

In [2]:
img_1 = cv2.imread("C:/Users/MR.H.BALAJEE/Downloads/Dalmatian puppy.jpg")

In [3]:
shp = img_1.shape
print(shp)

(250, 334, 3)


In [4]:
height,width = img_1.shape[:2]
print(height)
print(width)

250
334


In [5]:
centre = (height/2,width/2)
centre

(125.0, 167.0)

In [60]:
rotation_matrix = cv2.getRotationMatrix2D(center = centre,angle = 180,scale = 0.5)

In [61]:
print(rotation_matrix)

[[-5.000000e-01  6.123234e-17  1.875000e+02]
 [-6.123234e-17 -5.000000e-01  2.505000e+02]]


In [62]:
rotated_image = cv2.warpAffine(src = img_1, M = rotation_matrix, dsize = (width, height))

In [63]:
cv2.imshow("Original Image",img_1)
cv2.waitKey(0)
cv2.imshow("Rotated Image",rotated_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Translation Matrix

In [64]:
tx,ty = width/2,height/2
tx,ty

(167.0, 125.0)

In [66]:
Translation_Matrix = np.array([[1,0,tx],[0,1,ty]])

In [67]:
Translation_Matrix

array([[  1.,   0., 167.],
       [  0.,   1., 125.]])

In [68]:
Translated_Image = cv2.warpAffine(src = img_1, M = Translation_Matrix, dsize = (width, height))

In [70]:
cv2.imshow("Original Image",img_1)
cv2.waitKey(0)
cv2.imshow("Translated Image",Translated_Image)
cv2.waitKey(0)
cv2.destroyAllWindows()